services:
    geoip2.reader:
        class: GeoIp2\Database\Reader
        arguments: [ '%geoip2.cache%', '%geoip2.locales%' ]
        public: true

    GpsLab\Bundle\GeoIP2Bundle\Command\UpdateDatabaseCommand:
        arguments: [ '@filesystem', '%geoip2.url%', '%geoip2.cache%' ]
        public: false
        tags:
            - { name: console.command }
